# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sample

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTAnimation',
    'RCTActionSheet',
    'CxxBridge',
    'Core',
    'DevSupport',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
    # Add any other subspecs you want to use in your project
  ]

 
end
